//
//  StyleKitName.h
//  ProjectName
//
//  Created by AuthorName on 1/7/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas2;
+ (void)drawTony;
+ (void)drawTeslaInspires;
+ (void)drawJobsInspires;
+ (void)drawSpielberg;

@end
