//
//  StyleKitName.m
//  ProjectName
//
//  Created by AuthorName on 1/6/15.
//  Copyright (c) 2015 CompanyName. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StyleKitName.h"


@implementation StyleKitName

#pragma mark Initialization

+ (void)initialize
{
}

#pragma mark Drawing Methods

+ (void)drawCanvas1
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.871 green: 0.282 blue: 0.212 alpha: 1];
    CGFloat colorHSBA[4];
    [color getHue: &colorHSBA[0] saturation: &colorHSBA[1] brightness: &colorHSBA[2] alpha: &colorHSBA[3]];

    UIColor* color8 = [UIColor colorWithHue: colorHSBA[0] saturation: 1 brightness: colorHSBA[2] alpha: colorHSBA[3]];
    UIColor* color2 = [UIColor colorWithHue: 0.087 saturation: colorHSBA[1] brightness: colorHSBA[2] alpha: colorHSBA[3]];
    UIColor* color4 = [UIColor colorWithRed: 0.337 green: 0.588 blue: 0.737 alpha: 1];
    UIColor* color5 = [UIColor colorWithRed: 0.184 green: 0.318 blue: 0.408 alpha: 1];
    UIColor* color6 = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];

    //// Image Declarations
    UIImage* image = [UIImage imageNamed: @"image.jpg"];

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 320, 601)];
    [color8 setFill];
    [rectanglePath fill];


    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(87, 99, 140, 140)];
    CGContextSaveGState(context);
    [ovalPath addClip];
    CGContextScaleCTM(context, 1.0, -1.0);
    CGContextDrawTiledImage(context, CGRectMake(89, -99, image.size.width, image.size.height), image.CGImage);
    CGContextRestoreGState(context);
    [color4 setStroke];
    ovalPath.lineWidth = 4.5;
    [ovalPath stroke];


    //// Info Drawing
    CGRect infoRect = CGRectMake(33, 19, 249, 80);
    {
        NSString* textContent = @"Welcome to my GHP app.\nClick arround to learn about me";
        NSMutableParagraphStyle* infoStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        infoStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* infoFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: UIFont.labelFontSize], NSForegroundColorAttributeName: color6, NSParagraphStyleAttributeName: infoStyle};

        CGFloat infoTextHeight = [textContent boundingRectWithSize: CGSizeMake(infoRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: infoFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, infoRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(infoRect), CGRectGetMinY(infoRect) + (CGRectGetHeight(infoRect) - infoTextHeight) / 2, CGRectGetWidth(infoRect), infoTextHeight) withAttributes: infoFontAttributes];
        CGContextRestoreGState(context);
    }


    //// About Me Drawing
    CGRect aboutMeRect = CGRectMake(32.5, 250, 249, 36);
    UIBezierPath* aboutMePath = [UIBezierPath bezierPathWithRoundedRect: aboutMeRect cornerRadius: 15];
    [color5 setFill];
    [aboutMePath fill];
    [color2 setStroke];
    aboutMePath.lineWidth = 1;
    [aboutMePath stroke];
    {
        NSString* textContent = @"About Me";
        NSMutableParagraphStyle* aboutMeStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        aboutMeStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* aboutMeFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: aboutMeStyle};

        CGFloat aboutMeTextHeight = [textContent boundingRectWithSize: CGSizeMake(aboutMeRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: aboutMeFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, aboutMeRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(aboutMeRect), CGRectGetMinY(aboutMeRect) + (CGRectGetHeight(aboutMeRect) - aboutMeTextHeight) / 2, CGRectGetWidth(aboutMeRect), aboutMeTextHeight) withAttributes: aboutMeFontAttributes];
        CGContextRestoreGState(context);
    }


    //// interests Drawing
    CGRect interestsRect = CGRectMake(33.5, 295, 249, 36);
    UIBezierPath* interestsPath = [UIBezierPath bezierPathWithRoundedRect: interestsRect cornerRadius: 15];
    [color5 setFill];
    [interestsPath fill];
    [color2 setStroke];
    interestsPath.lineWidth = 1;
    [interestsPath stroke];
    {
        NSString* textContent = @"Interests\n";
        NSMutableParagraphStyle* interestsStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        interestsStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* interestsFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: interestsStyle};

        CGFloat interestsTextHeight = [textContent boundingRectWithSize: CGSizeMake(interestsRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: interestsFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, interestsRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(interestsRect), CGRectGetMinY(interestsRect) + (CGRectGetHeight(interestsRect) - interestsTextHeight) / 2, CGRectGetWidth(interestsRect), interestsTextHeight) withAttributes: interestsFontAttributes];
        CGContextRestoreGState(context);
    }


    //// Musica Drawing
    CGRect musicaRect = CGRectMake(32.5, 340, 249, 36);
    UIBezierPath* musicaPath = [UIBezierPath bezierPathWithRoundedRect: musicaRect cornerRadius: 15];
    [color5 setFill];
    [musicaPath fill];
    [color2 setStroke];
    musicaPath.lineWidth = 1;
    [musicaPath stroke];
    {
        NSString* textContent = @"Favorite Music";
        NSMutableParagraphStyle* musicaStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        musicaStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* musicaFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: color6, NSParagraphStyleAttributeName: musicaStyle};

        CGFloat musicaTextHeight = [textContent boundingRectWithSize: CGSizeMake(musicaRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: musicaFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, musicaRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(musicaRect), CGRectGetMinY(musicaRect) + (CGRectGetHeight(musicaRect) - musicaTextHeight) / 2, CGRectGetWidth(musicaRect), musicaTextHeight) withAttributes: musicaFontAttributes];
        CGContextRestoreGState(context);
    }


    //// a&h Drawing
    CGRect ahRect = CGRectMake(32.5, 385, 249, 36);
    UIBezierPath* ahPath = [UIBezierPath bezierPathWithRoundedRect: ahRect cornerRadius: 15];
    [color5 setFill];
    [ahPath fill];
    [color2 setStroke];
    ahPath.lineWidth = 1;
    [ahPath stroke];
    {
        NSString* textContent = @"Awards and Honors";
        NSMutableParagraphStyle* ahStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        ahStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* ahFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: ahStyle};

        CGFloat ahTextHeight = [textContent boundingRectWithSize: CGSizeMake(ahRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: ahFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, ahRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(ahRect), CGRectGetMinY(ahRect) + (CGRectGetHeight(ahRect) - ahTextHeight) / 2, CGRectGetWidth(ahRect), ahTextHeight) withAttributes: ahFontAttributes];
        CGContextRestoreGState(context);
    }


    //// Inspirations Drawing
    CGRect inspirationsRect = CGRectMake(32.5, 430, 249, 36);
    UIBezierPath* inspirationsPath = [UIBezierPath bezierPathWithRoundedRect: inspirationsRect cornerRadius: 15];
    [color5 setFill];
    [inspirationsPath fill];
    [color2 setStroke];
    inspirationsPath.lineWidth = 1;
    [inspirationsPath stroke];
    {
        NSString* textContent = @"Inspirations";
        NSMutableParagraphStyle* inspirationsStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        inspirationsStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* inspirationsFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: inspirationsStyle};

        CGFloat inspirationsTextHeight = [textContent boundingRectWithSize: CGSizeMake(inspirationsRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: inspirationsFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, inspirationsRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(inspirationsRect), CGRectGetMinY(inspirationsRect) + (CGRectGetHeight(inspirationsRect) - inspirationsTextHeight) / 2, CGRectGetWidth(inspirationsRect), inspirationsTextHeight) withAttributes: inspirationsFontAttributes];
        CGContextRestoreGState(context);
    }


    //// Social Media Drawing
    CGRect socialMediaRect = CGRectMake(32.5, 475, 249, 36);
    UIBezierPath* socialMediaPath = [UIBezierPath bezierPathWithRoundedRect: socialMediaRect cornerRadius: 15];
    [color5 setFill];
    [socialMediaPath fill];
    [color2 setStroke];
    socialMediaPath.lineWidth = 1;
    [socialMediaPath stroke];
    {
        NSString* textContent = @"Social Media ";
        NSMutableParagraphStyle* socialMediaStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        socialMediaStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* socialMediaFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: socialMediaStyle};

        CGFloat socialMediaTextHeight = [textContent boundingRectWithSize: CGSizeMake(socialMediaRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: socialMediaFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, socialMediaRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(socialMediaRect), CGRectGetMinY(socialMediaRect) + (CGRectGetHeight(socialMediaRect) - socialMediaTextHeight) / 2, CGRectGetWidth(socialMediaRect), socialMediaTextHeight) withAttributes: socialMediaFontAttributes];
        CGContextRestoreGState(context);
    }


    //// soure Code Drawing
    CGRect soureCodeRect = CGRectMake(33.5, 520, 249, 36);
    UIBezierPath* soureCodePath = [UIBezierPath bezierPathWithRoundedRect: soureCodeRect cornerRadius: 15];
    [color5 setFill];
    [soureCodePath fill];
    [color2 setStroke];
    soureCodePath.lineWidth = 1;
    [soureCodePath stroke];
    {
        NSString* textContent = @"Source Code for this App";
        NSMutableParagraphStyle* soureCodeStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        soureCodeStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* soureCodeFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: UIFont.smallSystemFontSize], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: soureCodeStyle};

        CGFloat soureCodeTextHeight = [textContent boundingRectWithSize: CGSizeMake(soureCodeRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: soureCodeFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, soureCodeRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(soureCodeRect), CGRectGetMinY(soureCodeRect) + (CGRectGetHeight(soureCodeRect) - soureCodeTextHeight) / 2, CGRectGetWidth(soureCodeRect), soureCodeTextHeight) withAttributes: soureCodeFontAttributes];
        CGContextRestoreGState(context);
    }
}

+ (void)drawCanvas2
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();

    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 0.871 green: 0.282 blue: 0.212 alpha: 1];
    CGFloat colorHSBA[4];
    [color getHue: &colorHSBA[0] saturation: &colorHSBA[1] brightness: &colorHSBA[2] alpha: &colorHSBA[3]];

    UIColor* color8 = [UIColor colorWithHue: colorHSBA[0] saturation: 1 brightness: colorHSBA[2] alpha: colorHSBA[3]];
    UIColor* color4 = [UIColor colorWithRed: 0.337 green: 0.588 blue: 0.737 alpha: 1];
    UIColor* color5 = [UIColor colorWithRed: 0.184 green: 0.318 blue: 0.408 alpha: 1];

    //// Rectangle 5 Drawing
    UIBezierPath* rectangle5Path = [UIBezierPath bezierPathWithRect: CGRectMake(-117, -19, 600, 600)];
    [color8 setFill];
    [rectangle5Path fill];


    //// Rectangle Drawing
    CGRect rectangleRect = CGRectMake(31, 115, 146, 75);
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: rectangleRect cornerRadius: 20];
    [color5 setFill];
    [rectanglePath fill];
    {
        NSString* textContent = @"Tony \nStark ";
        NSMutableParagraphStyle* rectangleStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        rectangleStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* rectangleFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: 21], NSForegroundColorAttributeName: UIColor.blackColor, NSParagraphStyleAttributeName: rectangleStyle};

        CGFloat rectangleTextHeight = [textContent boundingRectWithSize: CGSizeMake(rectangleRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: rectangleFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, rectangleRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(rectangleRect), CGRectGetMinY(rectangleRect) + (CGRectGetHeight(rectangleRect) - rectangleTextHeight) / 2, CGRectGetWidth(rectangleRect), rectangleTextHeight) withAttributes: rectangleFontAttributes];
        CGContextRestoreGState(context);
    }


    //// Rectangle 2 Drawing
    CGRect rectangle2Rect = CGRectMake(31, 215, 146, 75);
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRoundedRect: rectangle2Rect cornerRadius: 10];
    [color5 setFill];
    [rectangle2Path fill];
    {
        NSString* textContent = @"Steven \nSpielberg ";
        NSMutableParagraphStyle* rectangle2Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        rectangle2Style.alignment = NSTextAlignmentCenter;

        NSDictionary* rectangle2FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: 21], NSForegroundColorAttributeName: UIColor.blackColor, NSParagraphStyleAttributeName: rectangle2Style};

        CGFloat rectangle2TextHeight = [textContent boundingRectWithSize: CGSizeMake(rectangle2Rect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: rectangle2FontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, rectangle2Rect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(rectangle2Rect), CGRectGetMinY(rectangle2Rect) + (CGRectGetHeight(rectangle2Rect) - rectangle2TextHeight) / 2, CGRectGetWidth(rectangle2Rect), rectangle2TextHeight) withAttributes: rectangle2FontAttributes];
        CGContextRestoreGState(context);
    }


    //// Rectangle 3 Drawing
    CGRect rectangle3Rect = CGRectMake(31, 315, 146, 75);
    UIBezierPath* rectangle3Path = [UIBezierPath bezierPathWithRoundedRect: rectangle3Rect cornerRadius: 10];
    [color5 setFill];
    [rectangle3Path fill];
    {
        NSString* textContent = @"Nikolai\nTesla";
        NSMutableParagraphStyle* rectangle3Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        rectangle3Style.alignment = NSTextAlignmentCenter;

        NSDictionary* rectangle3FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: 21], NSForegroundColorAttributeName: UIColor.blackColor, NSParagraphStyleAttributeName: rectangle3Style};

        CGFloat rectangle3TextHeight = [textContent boundingRectWithSize: CGSizeMake(rectangle3Rect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: rectangle3FontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, rectangle3Rect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(rectangle3Rect), CGRectGetMinY(rectangle3Rect) + (CGRectGetHeight(rectangle3Rect) - rectangle3TextHeight) / 2, CGRectGetWidth(rectangle3Rect), rectangle3TextHeight) withAttributes: rectangle3FontAttributes];
        CGContextRestoreGState(context);
    }


    //// Rectangle 4 Drawing
    CGRect rectangle4Rect = CGRectMake(31, 415, 146, 75);
    UIBezierPath* rectangle4Path = [UIBezierPath bezierPathWithRoundedRect: rectangle4Rect cornerRadius: 10];
    [color5 setFill];
    [rectangle4Path fill];
    {
        NSString* textContent = @"Steve Jobs ";
        NSMutableParagraphStyle* rectangle4Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        rectangle4Style.alignment = NSTextAlignmentCenter;

        NSDictionary* rectangle4FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: 21], NSForegroundColorAttributeName: UIColor.blackColor, NSParagraphStyleAttributeName: rectangle4Style};

        CGFloat rectangle4TextHeight = [textContent boundingRectWithSize: CGSizeMake(rectangle4Rect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: rectangle4FontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, rectangle4Rect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(rectangle4Rect), CGRectGetMinY(rectangle4Rect) + (CGRectGetHeight(rectangle4Rect) - rectangle4TextHeight) / 2, CGRectGetWidth(rectangle4Rect), rectangle4TextHeight) withAttributes: rectangle4FontAttributes];
        CGContextRestoreGState(context);
    }


    //// Inspirations Drawing
    CGRect inspirationsRect = CGRectMake(84, 47, 134, 42);
    {
        NSString* textContent = @"Inspirations";
        NSMutableParagraphStyle* inspirationsStyle = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        inspirationsStyle.alignment = NSTextAlignmentCenter;

        NSDictionary* inspirationsFontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: 21], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: inspirationsStyle};

        CGFloat inspirationsTextHeight = [textContent boundingRectWithSize: CGSizeMake(inspirationsRect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: inspirationsFontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, inspirationsRect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(inspirationsRect), CGRectGetMinY(inspirationsRect) + (CGRectGetHeight(inspirationsRect) - inspirationsTextHeight) / 2, CGRectGetWidth(inspirationsRect), inspirationsTextHeight) withAttributes: inspirationsFontAttributes];
        CGContextRestoreGState(context);
    }


    //// Oval Drawing
    UIBezierPath* ovalPath = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(197, 115, 75, 75)];
    [UIColor.grayColor setFill];
    [ovalPath fill];
    [color4 setStroke];
    ovalPath.lineWidth = 3;
    CGFloat ovalPattern[] = {2, 2};
    [ovalPath setLineDash: ovalPattern count: 2 phase: 0];
    [ovalPath stroke];


    //// Oval 2 Drawing
    UIBezierPath* oval2Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(197, 215, 75, 75)];
    [UIColor.grayColor setFill];
    [oval2Path fill];
    [color4 setStroke];
    oval2Path.lineWidth = 3;
    CGFloat oval2Pattern[] = {2, 2};
    [oval2Path setLineDash: oval2Pattern count: 2 phase: 0];
    [oval2Path stroke];


    //// Oval 3 Drawing
    UIBezierPath* oval3Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(197, 315, 75, 75)];
    [UIColor.grayColor setFill];
    [oval3Path fill];
    [color4 setStroke];
    oval3Path.lineWidth = 3;
    CGFloat oval3Pattern[] = {2, 2};
    [oval3Path setLineDash: oval3Pattern count: 2 phase: 0];
    [oval3Path stroke];


    //// Oval 4 Drawing
    UIBezierPath* oval4Path = [UIBezierPath bezierPathWithOvalInRect: CGRectMake(197, 415, 75, 75)];
    [UIColor.grayColor setFill];
    [oval4Path fill];
    [color4 setStroke];
    oval4Path.lineWidth = 3;
    CGFloat oval4Pattern[] = {2, 2};
    [oval4Path setLineDash: oval4Pattern count: 2 phase: 0];
    [oval4Path stroke];


    //// Inspirations 2 Drawing
    CGRect inspirations2Rect = CGRectMake(84, 73, 134, 42);
    {
        NSString* textContent = @"Click for more info";
        NSMutableParagraphStyle* inspirations2Style = NSMutableParagraphStyle.defaultParagraphStyle.mutableCopy;
        inspirations2Style.alignment = NSTextAlignmentCenter;

        NSDictionary* inspirations2FontAttributes = @{NSFontAttributeName: [UIFont fontWithName: @"STHeitiTC-Medium" size: 13], NSForegroundColorAttributeName: UIColor.whiteColor, NSParagraphStyleAttributeName: inspirations2Style};

        CGFloat inspirations2TextHeight = [textContent boundingRectWithSize: CGSizeMake(inspirations2Rect.size.width, INFINITY)  options: NSStringDrawingUsesLineFragmentOrigin attributes: inspirations2FontAttributes context: nil].size.height;
        CGContextSaveGState(context);
        CGContextClipToRect(context, inspirations2Rect);
        [textContent drawInRect: CGRectMake(CGRectGetMinX(inspirations2Rect), CGRectGetMinY(inspirations2Rect) + (CGRectGetHeight(inspirations2Rect) - inspirations2TextHeight) / 2, CGRectGetWidth(inspirations2Rect), inspirations2TextHeight) withAttributes: inspirations2FontAttributes];
        CGContextRestoreGState(context);
    }
}

+ (void)drawTonyStark
{
    //// General Declarations
    CGContextRef context = UIGraphicsGetCurrentContext();


    //// Image Declarations
    UIImage* image2 = [UIImage imageNamed: @"image2.jpg"];

    //// Rectangle 2 Drawing
    UIBezierPath* rectangle2Path = [UIBezierPath bezierPathWithRect: CGRectMake(0, 0, 320, 568)];
    [UIColor.grayColor setFill];
    [rectangle2Path fill];


    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRect: CGRectMake(74, 217, 165, 166)];
    CGContextSaveGState(context);
    [rectanglePath addClip];
    [image2 drawInRect: CGRectMake(74, 217, image2.size.width, image2.size.height)];
    CGContextRestoreGState(context);
}

@end
